name: microservice

services:

  # Authentication db
  mysql:
    image: mysql:8.0
    container_name: auth
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_MYSQL_DATABASE}
      MYSQL_USER: ${AUTH_MYSQL_USER}
      MYSQL_PASSWORD: ${AUTH_MYSQL_PASSWORD}
    ports:
      - "3303:3306"


